//! Generated SDK client adapter — bridges AppContext to the co-generated SDK.
//!
//! Auto-generated by @fern-api/cli-generator. Do not edit by hand.

#![allow(dead_code)]

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use fern_cli_sdk::error::CliError;
use fern_cli_sdk::openapi::AppContext;
use fern_cli_sdk::sdk_executor::{CliExecutor, SdkError, SdkRequestExecutor};

// ---------------------------------------------------------------------------
// Executor adapter: CliExecutor → SDK RequestExecutor
// ---------------------------------------------------------------------------

struct CliExecutorAdapter(Arc<CliExecutor>);

impl athena_intelligence_api_sdk::RequestExecutor for CliExecutorAdapter {
    fn execute(
        &self,
        request: reqwest::Request,
    ) -> Pin<
        Box<
            dyn Future<Output = Result<reqwest::Response, Box<dyn std::error::Error + Send + Sync>>>
                + Send
                + '_,
        >,
    > {
        Box::pin(async move {
            SdkRequestExecutor::execute(&*self.0, request)
                .await
                .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)
        })
    }
}

// ---------------------------------------------------------------------------
// client — construct a fully-wired SDK root client
// ---------------------------------------------------------------------------

/// Build the SDK root client from the CLI's runtime context.
///
/// The returned client routes all HTTP through the CLI's executor, so
/// it inherits auth, retries, TLS, and global headers automatically.
pub fn client(ctx: &AppContext) -> athena_intelligence_api_sdk::api::ApiClient {
    let executor = ctx.build_sdk_executor();
    let adapter = Arc::new(CliExecutorAdapter(executor));
    let config = athena_intelligence_api_sdk::ClientConfig::default();
    let http_client = athena_intelligence_api_sdk::HttpClient::with_executor(
        adapter as Arc<dyn athena_intelligence_api_sdk::RequestExecutor>,
        config.clone(),
    );
    athena_intelligence_api_sdk::api::ApiClient {
        config,
        agents: athena_intelligence_api_sdk::api::AgentsClient {
            http_client: http_client.clone(),
            drive: athena_intelligence_api_sdk::api::resources::agents::DriveClient { http_client: http_client.clone() },
            general: athena_intelligence_api_sdk::api::resources::agents::GeneralClient { http_client: http_client.clone() },
            research: athena_intelligence_api_sdk::api::resources::agents::ResearchClient { http_client: http_client.clone() },
            sql: athena_intelligence_api_sdk::api::resources::agents::SqlClient { http_client: http_client.clone() },
        },
        aop: athena_intelligence_api_sdk::api::AopClient { http_client: http_client.clone() },
        assets: athena_intelligence_api_sdk::api::AssetsClient { http_client: http_client.clone() },
        collab_agents: athena_intelligence_api_sdk::api::CollabAgentsClient { http_client: http_client.clone() },
        computer: athena_intelligence_api_sdk::api::ComputerClient { http_client: http_client.clone() },
        databases: athena_intelligence_api_sdk::api::DatabasesClient { http_client: http_client.clone() },
        users: athena_intelligence_api_sdk::api::UsersClient { http_client: http_client.clone() },
        meetings: athena_intelligence_api_sdk::api::MeetingsClient { http_client: http_client.clone() },
        query: athena_intelligence_api_sdk::api::QueryClient { http_client: http_client.clone() },
        semantic_model: athena_intelligence_api_sdk::api::SemanticModelClient { http_client: http_client.clone() },
        sessions: athena_intelligence_api_sdk::api::SessionsClient { http_client: http_client.clone() },
        threads: athena_intelligence_api_sdk::api::ThreadsClient { http_client: http_client.clone() },
        toolkits: athena_intelligence_api_sdk::api::ToolkitsClient { http_client: http_client.clone() },
        tools: athena_intelligence_api_sdk::api::ToolsClient {
            http_client: http_client.clone(),
            calendar: athena_intelligence_api_sdk::api::resources::tools::CalendarClient { http_client: http_client.clone() },
            email: athena_intelligence_api_sdk::api::resources::tools::EmailClient { http_client: http_client.clone() },
            sheets: athena_intelligence_api_sdk::api::resources::tools::SheetsClient { http_client: http_client.clone() },
            structured_data_extractor: athena_intelligence_api_sdk::api::resources::tools::StructuredDataExtractorClient { http_client: http_client.clone() },
            tasks: athena_intelligence_api_sdk::api::resources::tools::TasksClient { http_client: http_client.clone() },
        },
        workspaces: athena_intelligence_api_sdk::api::WorkspacesClient { http_client: http_client.clone() },
    }
}

// ---------------------------------------------------------------------------
// block_on — async SDK call → sync handler result
// ---------------------------------------------------------------------------

/// Execute an async SDK operation from a synchronous custom-command handler.
///
/// Bridges the SDK's `ApiError` into the CLI's `CliError` so `?` works
/// naturally in handler bodies.
pub fn block_on<F, T>(future: F) -> Result<T, CliError>
where
    F: Future<Output = Result<T, athena_intelligence_api_sdk::ApiError>>,
{
    tokio::task::block_in_place(|| {
        let handle = tokio::runtime::Handle::current();
        handle.block_on(future).map_err(convert_api_error)
    })
}

fn convert_api_error(e: athena_intelligence_api_sdk::ApiError) -> CliError {
    match e {
        athena_intelligence_api_sdk::ApiError::Http { status, message } => CliError::Api {
            code: status,
            message,
            reason: http_status_reason(status).to_string(),
        },
        athena_intelligence_api_sdk::ApiError::Network(err) => {
            CliError::Other(anyhow::anyhow!("SDK network error: {err}"))
        }
        athena_intelligence_api_sdk::ApiError::Executor(boxed) => match boxed.downcast::<SdkError>() {
            Ok(sdk_error) => sdk_error.into_cli_error(),
            Err(other) => CliError::Other(anyhow::anyhow!("SDK executor error: {other}")),
        },
        other => CliError::Other(anyhow::anyhow!("SDK error: {other}")),
    }
}

fn http_status_reason(status: u16) -> &'static str {
    match status {
        400 => "badRequest",
        401 => "unauthorized",
        403 => "forbidden",
        404 => "notFound",
        408 => "requestTimeout",
        409 => "conflict",
        429 => "tooManyRequests",
        500 => "internalServerError",
        502 => "badGateway",
        503 => "serviceUnavailable",
        504 => "gatewayTimeout",
        _ => "httpError",
    }
}
